# Generated by Django 4.2.16 on 2024-10-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfcourses_app', '0002_golf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='golf',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
