# Generated by Django 4.2.16 on 2024-10-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfcourses_app', '0003_golf_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfSnacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('snacks', models.CharField(choices=[('C', 'Chips'), ('G', 'Glizzy'), ('B', 'Burger')], default='C', max_length=1)),
            ],
        ),
    ]
